### PR TITLE
added party host

### PR DESCRIPTION
**Pull request by ChaoticNeutralGnome**

### CODE REVIEW

**Comment by pikulet** [comment]
request to add rainbow text effect

**Comment by pikulet** [comment]
During a party,
- [x] Jailer can join the party
- [x] Jailed target cannot join the party
- [x] Mason can join the party
- [x] Cult can join the party
- [x] Mafia can join the party
- [x] Illuminati join the party

- [x] Can only host 1 party a game

**Comment by r3ndd** [comment]
@pikulet is this tested and ready to merge?

**Comment by pikulet** [comment]
i tested those pointers mentioned above, yes
the merge conflict is because of the priority file

PARTY_MEETING should be under day priority

**Comment by pikulet** [comment]
lgtm, I have sent an MR to your branch if you are lazy to merge master.

**Comment by pikulet** [comment]
This one needs an update to the priority file; move party under day priorities

**Pull request closed without merging**
