### PR TITLE
Added Trickster

### PR DESCRIPTION
**Pull request by starryburst**
Added a working trickster.

Crystal is now added.

#312 is PR for Crystal

### CODE REVIEW

**Comment by pikulet** [comment]
I would strongly recommend refactoring the cursed items to be like Gun.

#231

**Comment by starryburst** [comment]
> I would strongly recommend refactoring the cursed items to be like Gun.
> 
> #231

Should I do this in a seperate PR?

**Comment by pikulet** [comment]
Yes ideally separate PR and do that first, ensure that fab/ cutler/ blacksmith/ baker are working normally

**Comment by pikulet** [comment]
I am working on refactoring the items here #341 
You can merge this code and I'll do the refactoring afterwards.

**Comment by pikulet** [comment]
I would remove crystal until the enchantress PR is in, then just add crystal in as an extension of this role

**Comment by pikulet** [comment]
pending #341

**Review by pikulet — APPROVED** [review]

**Review by pikulet — APPROVED** [review]

**Pull request merged**
