### PR TITLE
[TESTED] Added mimic

### PR DESCRIPTION
**Pull request by ChaoticNeutralGnome**

### CODE REVIEW

**Comment by pikulet** [comment]
**mimic test**
- [ ] mimic town
- [ ] mimic mafia
- [ ] mimic witch
- [ ] still able to mimic after getting roleblocked
- [ ] (in future) mimic suited mafia

**Comment by pikulet** [comment]
village idiot/ blue will know if they have been mimiced because there is a "your role is villager" message that appears
 
 This *might* affect comp mechanics, I forgot the setup name that uses mimic. A blue will know they have been mimiced and can claim it.

**Comment by ChaoticNeutralGnome** [comment]
> **village idiot/ blue will know if they have been mimiced because there is a "your role is villager" message that appears**
> 
> This _might_ affect comp mechanics, I forgot the setup name that uses mimic. A blue will know they have been mimiced and can claim it. It depends if we want to add it.
> 
> We can consider passing in **noAlert=true** to the setRole function.

possibly we can implement logic in setRole to not alert if they have the same self appearance they did before?

**Comment by pikulet** [comment]
yeah i think just adding something in the revealToSelf function would be good,

either change 

revealToSelf(alertType) = "never", "always", "onChange"

or just add another param like revealToSelf(noAlert, alertOnChange)

**Comment by ChaoticNeutralGnome** [comment]
Updated setRole to not reveal if self appearance is the same before and after

**Comment by pikulet** [comment]
- [x] setRole reveal when appearance changes
- [x] setRole no reveal when appearance remains the same

**Pull request merged**
