### PR TITLE
Made the emote page look nicer

### PR DESCRIPTION
**Pull request by PatakiGergo**
Made the emote page look nicer

image

### CODE REVIEW

**Review by Kaltzisp — CHANGES_REQUESTED** [review]
`.emote { margin-left: 4px }` results in in-game emotes having slightly weird spacing, can I suggest that you replace this with `.emote-list .emote { margin-left: 4px; }`? Otherwise I'm very happy with this! Looks great :D
image

**Comment by PatakiGergo** [comment]
Hopefully it works now as intended

**Review by Kaltzisp — DISMISSED** [review]

**Comment by pikulet** [comment]
Can someone help format this code to use the correct number of tabs/ spaces?

**Review by pikulet — APPROVED** [review]

**Comment by pikulet** [comment]
@Kaltzisp run the linter later, I've cleaned this PR up

**Review by Kaltzisp — APPROVED** [review]

**Pull request merged**
