### PR TITLE
feat: add dark mode

### PR DESCRIPTION
**Pull request by DrSharky**
The commit feels pretty thorough. Feel free to review for anything I missed or feels wrong.
Adds a switch in the user settings to switch to a dark mode version. It should be a total conversion.

### CODE REVIEW

**Comment by pikulet** [comment]
how should we handle users who have purchased colours, right now 

say colours are from 0 (black) to 1 (white).
we allow colours <= 0.7

should we 1. flip the colours to the contrasting one or 2. add a check for 0.3 <= colour <= 0.7

**Comment by pikulet** [comment]
Fixes #66

**Comment by r3ndd** [comment]
I think the best option is 1. The simplest way I can think of to do it is to use a color library to convert the color to HSL format and invert the L value.

**Comment by DrSharky** [comment]
> how should we handle users who have purchased colours, right now dark colours cannot be seen on the dark bg
> 
> current colour logic: colours are scored from 0 (black) to 1 (white). we allow text colours <= 0.7
> 
> some ideas
> 
> 1. flip the purchased colours to the contrasting one, this is how dark mode extensions do it
> 2. add a check for 0.3 <= colour <= 0.7, so the purchased colours can be seen on both dark and light backgrounds
> 3. add a separate configuration for dark mode and light mode colours, so i can pick yellow in dark mode and dark blue in light mode
> 4. add a glow behind the text (suggestion by lechuck but not sure how this would look)
> 5. always display white text in dark mode (invalidate purchased colours)
> 
> the easiest solution rn is to implement method 2 or 5, and afterwards we can tweak it according to feedback

Maybe I'm not understanding what you guys are talking about...
Why would we change the colors? Aren't the users choosing the colors they want? 
Besides the point of why, I guess I'll ask what colors are we flipping? And who would we be flipping them for?

**Comment by pikulet** [comment]
Yes that is right. Dark purchased colours currently cannot be seen in dark mode.

**Comment by DrSharky** [comment]
This should be ready for another review.

**Comment by DrSharky** [comment]
Ok, NOW it should be ready. I figured out testing the chatbox.

**Comment by pikulet** [comment]
image
image

stumbled upon it; admin box is not black

**Review by pikulet — CHANGES_REQUESTED** [review]
everything is great except "listing mods in dark mode". i've commented with the relevant css

**Review by pikulet — APPROVED** [review]

**Review by ChaoticNeutralGnome — APPROVED** [review]

**Pull request merged**
