### PR TITLE
Added Killer Bee (T*rrorist) and Caroler

### PR DESCRIPTION
**Pull request by R9H9**
I accidentally deleted the other branch so I'll make a new pull request with the changes.

### CODE REVIEW

**Comment by pikulet** [comment]
You might be able to store data in this.actor.role.data, like how oracle does it in "RevealOnDeath".

**Comment by r3ndd** [comment]
There's got to be a better name than Exploder. What about Killer Bee? (dies after stinging)

**Comment by r3ndd** [comment]
I'll go ahead an make the change and it can always be updated later.

**Comment by r3ndd** [comment]
I'm already working on it. Please don't push updates while I am.

**Comment by pikulet** [comment]
hey @R9H9 some thoughts on the repeated target.

I think the previous target should also be excluded in the carol meeting options. I accidentally click the same person twice there is no indication that they won't get the carol.

Either that or make it intentional that players have to remember who they caroled. When you carol the same person twice, a message can be given to the caroler to let them know that it didn't go through.

**Comment by r3ndd** [comment]
> Sorry.

It's fine, it's just that I'm going to be overwriting most of the files you changed with my fixes after testing.

**Pull request merged**
