### PR TITLE
feat: add anarchist role

### PR DESCRIPTION
**Pull request by pikulet**
- [x] if person is shot, they no longer appear in the potato passing list
- [x] if person holding potato is dead via shot, the potato no longer explodes
- [x] able to win when last two alive
- [x] able to win when kills two people via potato
- [x] played a game with multiple potatoes passed to the same person

this is noVeg, not mustAct because some people want to NL and hold the bomb

### CODE REVIEW

**Comment by pikulet** [comment]
this is noVeg, not mustAct because some people want to NL and hold the bomb

**Comment by pikulet** [comment]
the anarchist can technically win by
1. being explosive and holding a bomb
2. dying and reviving twice

this is because the code doesn't differentiate between the death from bomb and ticking bomb

a fix i had in mind was to add a new death type but i figured it's better to have as universal death types as possible

**Review by R9H9 — DISMISSED** [review]
I think this should be fine.

**Comment by pikulet** [comment]
Any thoughts on the edge case of the anarchist? Because I'm checking for deathType "bomb".

Alternatively we can pass in itemName as another param to the death emit? Seems unnecessarily complex for the edge case.

**Comment by minokr** [comment]
> a fix i had in mind was to add a new death type but i figured it's better to have as universal death types as possible

I think a good fix would be to add "giver" to the Item class, defaulted to null. There's a lot of roles which give items so this could be very useful to have for future features.

**Review by R9H9 — DISMISSED** [review]
i guess we can fix things in another commit if need be
seems fine to me

**Review by R9H9 — APPROVED** [review]

**Comment by R9H9** [comment]
actually i have a better idea.

**Comment by R9H9** [comment]
we can create a new pr once things are fixed.

**Pull request closed without merging**
