### PR TITLE
refactor: reflavour roles to match em

### PR DESCRIPTION
**Pull request by R9H9**
This is for #343.

### CODE REVIEW

**Review by plokky — DISMISSED** [review]
No crashes hosting a game with all these roles, and all text I could think to check looks good

**Comment by pikulet** [comment]
Roles affected:

Jester -> Fool
Knight -> Bulletproof
Seer -> Detective
Babushka -> Granny
Suspect -> Miller
Illuminati -> Templar
Archer -> Hunter

**Review by pikulet — APPROVED** [review]

**Review by pikulet — DISMISSED** [review]

**Comment by pikulet** [comment]
Change icons after. The roles.png file is hard to manage + @TheBeepich has an existing PR that modifies it.

**Review by DrSharky — DISMISSED** [review]

**Comment by DrSharky** [comment]
Resolved the conflicts for the mafia.test.js.

**Comment by pikulet** [comment]
Fixed jester test case, now npm test passes everything.

**Review by pikulet — APPROVED** [review]

**Review by starryburst — APPROVED** [review]

**Pull request merged**
