### PR TITLE
fixed stun crash

### PR DESCRIPTION
**Pull request by ChaoticNeutralGnome**

### CODE REVIEW

**Comment by pikulet** [comment]
I'm quite certain that I tested this interaction though..
Is it a different env that cause this to not get picked up? :< sorry about it

**Comment by r3ndd** [comment]
I think it would be cleanest to modify Effect.js's queueActions() to resemble the one in Role.js. Then follow a card like Dream.js to see the format of the object that should be added to Stun.js's actions array.

**Comment by r3ndd** [comment]
It looks like Poison.js should be refactored in a similar way.

**Comment by r3ndd** [comment]
I'll merge for now though.

**Pull request merged**
