### PR TITLE
added-mastermind

### PR DESCRIPTION
**Pull request by ChaoticNeutralGnome**

### CODE REVIEW

**Comment by ChaoticNeutralGnome** [comment]
Currently only the mafia meeting has the "exclude mafia targets" functionality removed by mastermind. I don't know a way to remove all of the other ones without doing each one individually.

**Comment by pikulet** [comment]
**mastermind tests**
- [ ] causes mafia meeting to be anonymous
- [ ] wins instead of mafia
- [ ] when mastermind dies, the mafia meeting is no longer anonymous
- [ ] when mastermind dies, the mafia can still win

**Comment by pikulet** [comment]
> Currently only the mafia meeting has the "exclude mafia targets" functionality removed by mastermind. I don't know a way to remove all of the other ones without doing each one individually.

I'm assuming you're referring to anonymising lookout/ scout meetings and so on.

The solution in my mind isn't elegant, and is similar to the butterfly logic.

1. When roles are assigned, loop through all players and check their meetings.
2. If a meeting excludes mafia, remove that exclusion. Remember all the meetings that have been changed.
3. When the mastermind dies, undo the changes including anonymising the mafia meeting

**Comment by ChaoticNeutralGnome** [comment]
> > Currently only the mafia meeting has the "exclude mafia targets" functionality removed by mastermind. I don't know a way to remove all of the other ones without doing each one individually.
> 
> I'm assuming you're referring to anonymising lookout/ scout meetings and so on.
> 
> The solution in my mind isn't elegant, and is similar to the butterfly logic.
> 
> 1. When roles are assigned, loop through all players and check their meetings.
> 2. If a meeting excludes mafia, remove that exclusion. Remember all the meetings that have been changed.
> 3. When the mastermind dies, undo the changes including anonymising the mafia meeting

I think it's fine how it is for now

**Review by pikulet — APPROVED** [review]
lgtm, 
- i honestly feel that there is no need to remove mafia target from roles, but you can create an enhancement ticket for that!

- you can clean the priority file if you want (undo those newlines)

**Review by DrSharky — APPROVED** [review]

**Pull request merged**
