### PR TITLE
[TESTED] added The Thing (werewolf)

### PR DESCRIPTION
**Pull request by ChaoticNeutralGnome**

### CODE REVIEW

**Comment by pikulet** [comment]
- [ ] Able to eat suited roles like Godfather
- [ ] Able to eat mafia
- [ ] Not able to eat granny
- [ ] Able to eat granny when immune (?) shouldn't be allowed right, granny needs a stronger kill type
- [ ] Gains day immunity cannot be voted off
- [ ] Gains sunset immunity (cannot be shot by archer)
- [ ] Gains night immunity (cannot be killed)

**Comment by ChaoticNeutralGnome** [comment]
In EM ww didn't gain night immunity they could still be killed the night they ate

**Comment by pikulet** [comment]
lgtm

**Comment by r3ndd** [comment]
@ChaoticNeutralGnome I'm really confused about the purpose of the listeners that modify the meeting targets. There's a "roles" inputType for the meeting which should be what you want.

**Comment by ChaoticNeutralGnome** [comment]
> @ChaoticNeutralGnome I'm really confused about the purpose of the listeners that modify the meeting targets. There's a "role" inputType for the meeting which should be what you want.

I wasn't aware of that input type, is it dynamic with the changing roles in the game?

**Comment by r3ndd** [comment]
Yeah this is the first role to use it. Also there was a bug with the "role" inputType on the frontend that I fixed. It looks good to go now.

**Comment by ChaoticNeutralGnome** [comment]
> Yeah this is the first role to use it. Also there was a bug with the "role" inputType on the frontend that I fixed. It looks good to go now.

Tailor uses the same target list and could also be updated

**Pull request merged**
