### PR TITLE
Allow leader to put themself on team and have spies know each other

### PR DESCRIPTION
**Pull request by ChaoticNeutralGnome**

### CODE REVIEW

**Comment by ChaoticNeutralGnome** [comment]
I'm using VSCode, 4 spaces I thought that was standard

**Comment by ChaoticNeutralGnome** [comment]
The only changes I've made in this commit are removing "members" from exclude: ["members"] for Leader, adding the KnowsSpies card and adding KnowsSpies to Spies

**Comment by ChaoticNeutralGnome** [comment]
I fixed the indentation for this commit and turned on Detect Indentation From Content on VSCode

**Comment by r3ndd** [comment]
Thanks! It would probably be best if someone refactored the tabs to spaces. I think the main server uses spaces while the game server uses tabs for some reason.

**Pull request merged**
