### PR TITLE
Added Auto Dark Mode

### PR DESCRIPTION
**Pull request by R9H9**
I'm added auto dark mode, based off @DrSharky's #189.

### CODE REVIEW

**Comment by pikulet** [comment]
If you want to try your hand at it, you can lookup how to force the css to reload.

https://stackoverflow.com/questions/72190986/react-native-how-to-reload-colors-based-on-dark-mode-and-light-mode

**Comment by DrSharky** [comment]
Looks like it works nicely. I'll have a review tomorrow morning.

**Comment by pikulet** [comment]
nice work! i'll have a review soon too~

**Review by pikulet — APPROVED** [review]
worked for me

**Comment by pikulet** [comment]
That's not necessary, this PR is fine you can leave it pending more reviews.

**Review by DrSharky — APPROVED** [review]

**Pull request merged**
