### PR TITLE
[TESTED] added lightkeeper

### PR DESCRIPTION
**Pull request by ChaoticNeutralGnome**

### CODE REVIEW

**Comment by pikulet** [comment]
the only thing to test for this is killing LK + witch on the same night, the eclipse should only last 1 day still

**Comment by pikulet** [comment]
tested the above, lgtm.

**Comment by r3ndd** [comment]
@ChaoticNeutralGnome what's your name on the site btw?

**Comment by ChaoticNeutralGnome** [comment]
> @ChaoticNeutralGnome what's your name on the site btw?

riskitforthebiscuit

**Pull request merged**
