### PR TITLE
[TESTED] added prophet

### PR DESCRIPTION
**Pull request by ChaoticNeutralGnome**

### CODE REVIEW

**Comment by ChaoticNeutralGnome** [comment]
I can refactor the selection to use text fields whenever those are implemented

**Comment by pikulet** [comment]
- [ ] win with village
- [ ] win with mafia
- [ ] loses when everyone dies except itself

**Comment by pikulet** [comment]
it cannot predict archer snipe, i don't know if we want to add so many sunset options there... I honestly think this is a LGTM.

**Comment by pikulet** [comment]
@ChaoticNeutralGnome i am done testing this role, it's a LGTM except for archer snipe.

I honestly don't think we want to spam the options with all the sunsets just to allow prophet to benefit from such a win.

**Comment by ChaoticNeutralGnome** [comment]
> @ChaoticNeutralGnome i am done testing this role, it's a LGTM except for archer snipe, where the game would end on "Sunset"
> 
> I honestly don't think we want to spam the options with all the sunsets just to allow prophet to benefit from such a win.

I think that's fine. Ideally archer will be reworked when instant meetings are possible IMO

**Review by DrSharky — APPROVED** [review]

**Review by starryburst — APPROVED** [review]

**Comment by starryburst** [comment]
Sorry idk what happened I was trying to resolve the conflicts idk why it dismissed the reviews its ready to be merged

**Review by starryburst — APPROVED** [review]

**Review by DrSharky — APPROVED** [review]

**Pull request merged**
