### PR TITLE
Arsonist & Dreamer

### PR DESCRIPTION
**Pull request by gameshowmaster**
First draft of arsonist. I made Gasoline and Match their own separate items. If that's not ideal I can implement another way. Gasoline as an item would also allow for a "firefighter" type role to remove the item. Could also be easily reimplemented for Medusa (visitors become stone).

Wasn't sure if vest should protect against arsonist. Standard consensus seems to be "no".

- [x] make non-meeting
- [x] Don't reveal maf partners

### CODE REVIEW

**Comment by gameshowmaster** [comment]
I broke it. Hold please

**Comment by plokky** [comment]
hey i dont know where to dm you so ill mention it here - the mafia partner reveal is done in the `listener`s in the card `WinWithMafia` - you can probably just add an exception in the `if` to not do that if it's the arsonist role

**Comment by gameshowmaster** [comment]
> hey i dont know where to dm you so ill mention it here - the mafia partner reveal is done in the `listener`s in the card `WinWithMafia` - you can probably just add an exception in the `if` to not do that if it's the arsonist role

Thank you! I ended up making a new toggle/Card "Oblivious" for this purpose and adding it into the core

**Comment by gameshowmaster** [comment]
Thanks to the excellent work @R9H9 did on Caroler I was able to repurpose its card as "Dream" and make Dreamer.

**Pull request merged**
