### PR TITLE
ui fix: add 70% height limit on long whisper/contact list

### PR DESCRIPTION
**Pull request by pikulet**
[large screen.webm](https://user-images.githubusercontent.com/24848927/212448828-afda850d-bba6-47db-bad3-c2f9937ab20c.webm)

[small screen.webm](https://user-images.githubusercontent.com/24848927/212449046-ba950658-405f-4545-9440-0c69f0ef595b.webm)

### CODE REVIEW

**Comment by pikulet** [comment]
I wouldn't remove dead people from the contact list because of revival mechanics.

**Comment by r3ndd** [comment]
@pikulet what's your on-site username?

**Comment by pikulet** [comment]
my name is eggsushi but u already gave me a name change, thank you

**Comment by r3ndd** [comment]
Oh I was looking to give you tokens for this bug bounty.

**Comment by pikulet** [comment]
oh tysm rend!

**Pull request merged**
