### PR TITLE
[TESTED] Added cutler and snowman and fabricator

### PR DESCRIPTION
**Pull request by ChaoticNeutralGnome**

### CODE REVIEW

**Comment by pikulet** [comment]
**fabricator tests**
- [ ] Cursed Snowball roleblock the thrower
- [ ] Cursed Armour does not protect the holder
- [ ] Cursed Armour + regular armour in the same night will save the attacked person
- [ ] Cursed Gun backfires
- [ ] Cursed Knife poisons person on d1, they die on the morning announcement of d2

cutler tests
- [ ] knife on d1 kill the target at the end of n2

snowman tests
- [ ] able to snowball others
- [ ] cannot be snowballed

**Comment by pikulet** [comment]
will you want to combine "cursed" as a property of snowball, bread, armor, knife?

**Comment by ChaoticNeutralGnome** [comment]
I think it would be easier to refactor after being merged

**Comment by pikulet** [comment]
lgtm

**Comment by r3ndd** [comment]
What is the current testing process being used? Right now the roles.js object isn't valid JSON, which is preventing the main process from even starting and I can't imagine the games process getting much further.

**Comment by r3ndd** [comment]
I'm guessing it probably happened during one the merges.

**Pull request merged**
