### PR TITLE
feat: add role markers

### LINKED ISSUE #333: feat(ui): add role markers
# (6) Role Markers

image

Clicking the `?` (**QUESTION MARK**) icon SHOULD ALLOW you to 'guess' the player's role.
- Clicking `?` reveals a dropdown containing ONLY roles included in the currently played setup
- BOTH alive & dead players can guess 
- the UI should indicate all roles you are currently guessing, in ANY REASONABLE way* _(it's up to you, we don't have a designer)_

*example:
image

# EM Example

image
---
image

https://www.youtube.com/watch?v=tbJe7giS7JY&t=513s

### PR DESCRIPTION
**Pull request by pikulet**

### CODE REVIEW

**Comment by pikulet** [comment]
my first time using react context, please give me feedback on how to make it better. 

In particular, i am using rolecount in a nested manner. Rolecount on the ? icon , and Rolecount again on the prediction list in the popover. 

I found that checking useContext(game) doesn't load in the second instance that's why i passed in the toggle function as a props. 

And to distinguish between the first and second case, I renamed the toggle function's props in the popover

**Comment by pikulet** [comment]
I also made it such that a revealed role cannot be guessed. This isn't very good for situations like yakking a revealed role.

However, I wanted to incorporate such logic into it such that if you guessed someone's role and their real role gets revealed  the guesses update. Let me know your thoughts on how to design such a UI.

**Comment by pikulet** [comment]
**closed roles example (6 person game but shows all roles in setup)**

can only make predictions on unknown roles

[rolemarker-closed.webm](https://user-images.githubusercontent.com/24848927/223500641-85bf5062-a7f9-4909-ac5d-f5d55494dd7c.webm)

**open roles example (fixed number of roles and people in the game)**

[rolemarker-open.webm](https://user-images.githubusercontent.com/24848927/223500651-e0b11900-65e8-4ba9-8314-0a794b004a1a.webm)

**light mode example (the ? is hard to see, but red seemed too glaring)**

image

**predicting, then the role gets revealed**

[predict reveal.webm](https://user-images.githubusercontent.com/24848927/223510150-189bd968-b5f9-41ce-a584-684eac312f3f.webm)

Resolves #333 

**question - data lost on refresh?**
Is it normal for the role markers made to be lost upon refreshing? Should I save it to localStorage?

**Comment by pikulet** [comment]
[Screencast from 15-03-2023 20:02:02.webm](https://user-images.githubusercontent.com/24848927/225303530-c122ee39-c6d9-4cbc-8900-b1492d2a66b2.webm)

- Able to make role predictions, with the ? icon showing that it's a prediction
- When you "clear" the prediction, it will either show you (1) the revealed role or (2) the empty ?
- Able to predict for dead/ revealed roles (in case you think there's tailor etc)

**Comment by pikulet** [comment]
The only problem now is that you have to scroll over the small icon to see the description.

(before)
image

(after)
image

**Comment by pikulet** [comment]
@DrSharky made a good suggestion, the "clear role marker" option should show "?" instead of the empty body

**Comment by pikulet** [comment]
Improvements:
- When a role is revealed, overwrite the prediction
- Save the data on refreshing

**Review by DrSharky — APPROVED** [review]
I just would like to comment that the question mark is not very visible on dark mode.
We can add a lighter question mark in the roles.png and make the styling variable on the mode chosen. But I think we can do this for now still. Request my review again or DM me if you want to change that before merging this PR.

**Comment by pikulet** [comment]
I thought it was the opposite, it's easy to see in darkmode but hard to see in light mode. 

I want to use the same one in both modes, probably getting an icon designer to make it nicer like how the oneshot/armoured modifiers currently look.

**Comment by DrSharky** [comment]
> I thought it was the opposite, it's easy to see in darkmode but hard to see in light mode. Anyhow, I want to use the same one in both modes.
> 
> (p.s. there is a hidden comment where you can see how it looks on dark mode, scroll all the way up)
> 
> I'm not changing it because I want an icon designer to make it nicer like how the oneshot/armoured modifiers currently look. I made this using a font + border only.

This is the question mark that I am talking about, not the smaller yellow one.
cap

**Comment by pikulet** [comment]
I'll add a white mode version after. The question mark was originally there.

**Comment by pikulet** [comment]
#547 filed the black question mark issue

**Comment by pikulet** [comment]
image

fixed the size of it

**Review by starryburst — APPROVED** [review]

**Review by starryburst — APPROVED** [review]

**Review by DrSharky — APPROVED** [review]

**Pull request merged**
