### PR TITLE
added clockmaker

### PR DESCRIPTION
**Pull request by ChaoticNeutralGnome**

### CODE REVIEW

**Comment by pikulet** [comment]
- [ ] able to get extra life at 9
- [ ] able to win at 12
- [ ] instantly dies at 3

**Comment by DrSharky** [comment]
I tested this out. So far, the win cons work. Last 2 alive or clock gets to 12.
The instantly dying at 3 works.
The extra lives mostly work. I found that you still die to arsonist if you have an extra life.

**Comment by ChaoticNeutralGnome** [comment]
> I tested this out. So far, the win cons work. Last 2 alive or clock gets to 12. The instantly dying at 3 works. The extra lives mostly work. I found that you still die to arsonist if you have an extra life.

There was a bug where lighting a match didn't have a kill label so if you were on this branch that's probably why, but its been fixed in master

**Comment by DrSharky** [comment]
> > I tested this out. So far, the win cons work. Last 2 alive or clock gets to 12. The instantly dying at 3 works. The extra lives mostly work. I found that you still die to arsonist if you have an extra life.
> 
> There was a bug where lighting a match didn't have a kill label so if you were on this branch that's probably why, but its been fixed in master

It also it not invincible to dying with lover with an extra life.

**Comment by ChaoticNeutralGnome** [comment]
> > > I tested this out. So far, the win cons work. Last 2 alive or clock gets to 12. The instantly dying at 3 works. The extra lives mostly work. I found that you still die to arsonist if you have an extra life.
> > 
> > 
> > There was a bug where lighting a match didn't have a kill label so if you were on this branch that's probably why, but its been fixed in master
> 
> It also is not invincible to dying with lover with an extra life.

Yeah lover doesn't check for kill immunity before killing, neither does clockmaker at 6. We should probably standardize some of these role interactions that were unclear from EM

**Review by pikulet — APPROVED** [review]

**Comment by pikulet** [comment]
I personally think that doctor should not save CM at 3, and CM cannot become 3pm on virgin night since there are no deaths.

**Comment by ChaoticNeutralGnome** [comment]
Can we merge this in, then I'll make a separate PR adding power and dominate checks to lover/CM

**Review by pikulet — APPROVED** [review]

**Review by DrSharky — APPROVED** [review]

**Pull request merged**
