### PR TITLE
refactor(ui): Fixed the alert on mobile not being centered

### PR DESCRIPTION
**Pull request by KaIakaua**
I don't see any issues so I guess this is okay.
First attempt of coding on Windows using GitHub Desktop so I can maybe blame anything wrong on that.

### CODE REVIEW

**Comment by KaIakaua** [comment]
I will have to learn the organization for the titles but i'm guessing this one is refactor(ui):

**Comment by pikulet** [comment]
dw about title, im just trying to follow conventional commits - https://www.conventionalcommits.org/en/v1.0.0/

**Comment by pikulet** [comment]
**before**
image

**after**
image

**Review by pikulet — APPROVED** [review]

**Comment by KaIakaua** [comment]
Oh it's still on the way of the buttons a little bit, huh

**Comment by pikulet** [comment]
oh you want it to be totally above the buttons?

**Comment by KaIakaua** [comment]
it would be nice

**Comment by pikulet** [comment]
what browser are you using? most browsers let you toggle the size for testing. e.g. firefox

image

**Comment by KaIakaua** [comment]
I did that and it looked okay actually, idk what happened, firefox and Opera GX.

**Comment by KaIakaua** [comment]
I think that should do it.

**Comment by pikulet** [comment]
image

**Review by pikulet — APPROVED** [review]

**Review by DrSharky — APPROVED** [review]

**Pull request merged**
