### PR TITLE
Adding alien

### PR DESCRIPTION
**Pull request by plokky**
Branched off Sharky in #10 and added in a few fixes for this. Old EM alien role that probes every night, and wins if everyone is probed. Can joint with anything or win solo.

In EM the alien starts with a probe, I changed it to being an alien satisfies win condition as well, because things get whacky with a mimic/old maid.

Tested this with town winning with an alien alive with no win con, town jointing with alien both alive and dead, alien jointing with mafia, and alien jointing with monsters.

### CODE REVIEW

**Comment by plokky** [comment]
i dug around more and realize this could be done with a probe item, idk if that's your preference or not, i can make the change if so

**Comment by r3ndd** [comment]
Thanks, I'm going to refractor this tomorrow but overall it's looking good.

**Comment by r3ndd** [comment]
I made it so town won't win as long as an alien is alive, which hopefully gives the alien a better chance of probing everyone.

**Comment by ChaoticNeutralGnome** [comment]
> I made it so town won't win as long as an alien is alive, which hopefully gives the alien a better chance of probing everyone.

I think this change is a mistake. It makes town more likely to kill alien, making it weaker overall.

**Pull request merged**
