### PR TITLE
Added snoop

### PR DESCRIPTION
**Pull request by ChaoticNeutralGnome**

### CODE REVIEW

**Comment by pikulet** [comment]
(to be verified)
- [ ] Can detect empty inventory
- [ ] Can detect multiple items
- [ ] Can detect gun
- [ ] Can detect multiple gun
- [ ] Detects asso gun as normal gun (don't think this check passes now, should assogun be detected as normal gun?)
- [ ] Can detect bomb
- [ ] Can detect gasoline
- [ ] Can detect handcuff the night the target is jailed (by right snoop is last, it should drop before snoop checks)
- [ ] Can detect match
- [ ] Can detect unused orange
- [ ] Can detect orange the night the target is in the hotspring (by right snoop is last, it should drop before snoop checks)
- [ ] Can detect armour the night it is shattered (by right snoop is last, it should drop before snoop checks)

**Comment by pikulet** [comment]
hey risk, can you change priority snoop and use

PRIORITY_INVESTIGATIVE_AFTER_RESOLVE_DEFAULT

instead? thanks ^^

**Comment by ChaoticNeutralGnome** [comment]
removed specific priority and merged

**Comment by pikulet** [comment]
Tested this role, a small issue is that AssoGun appears as AssoGun to the snoop. This is an OK mechanic to me, but I want to hear what you think risk~

**Comment by ChaoticNeutralGnome** [comment]
I think that could easily be changed by changing the name of assogun to match gun if that were the intended behavior. IDK which way would be better. I could also update it to count numbers of items instead of repeating them, the string for that was kind of just a placeholder.

**Comment by r3ndd** [comment]
I went ahead and removed the count thing for items, as it makes it difficult to have close to proper grammar.

**Pull request merged**
