### PR TITLE
added butterfly

### PR DESCRIPTION
**Pull request by ChaoticNeutralGnome**

### CODE REVIEW

**Comment by pikulet** [comment]
- related to the mimic alert, if someone's role didn't change they still get the role alert, but i think for butterfly it's ok to keep it
- needs to account for amnesiac becoming butterfly

**Comment by pikulet** [comment]
cards have an init() function that can be used, see Games/core/Role.js#L64

**Comment by pikulet** [comment]
for the amnesiac-butterfly interaction --
i saw a Card.init() function called in Games/core/Role.js#L64 that might be useful

it's tricky because the real butterfly can only initialise the roles after all the roles have been assigned (i.e. for a real butterfly, card.init() is called before all players get their roles)

I've tested this PR so if this is the only issue we can file it as a separate bug report too.

**Comment by pikulet** [comment]
- tested on mason and cult conversions; works ok

**roles that don't change shouldn't be reset** 

It causes some role data to be lost (e.g. orc, caroler), not sure if it is an intentional mechanic

**needs to account for amnesiac becoming butterfly**

- game breaks because amn-butterfly doesn't have the "rolesAssigned" event
- i think we should just emit "rolesAssigned" again

**Comment by ChaoticNeutralGnome** [comment]
I think it's fine for their to be some side effects of resetting roles like double guns and no orc target. That makes the role have more effect on the game. 

As for the amn bug I can think of 3 ways to solve it:
1. The BecomeDeadRole card could pass in roleData from the target. Old maid already uses roleData so we should have some consistency on whether it is passed or not when using setRole. 
2. We could add the role storage to init as well, this would have the side effect of not making the roles what they were whenever the game started, but rather whenever the butterfly was set. No necessarily worse, but different. 
3. I haven't looked into this, but possibly the game history stores roles and we could use that instead of something tied to role data.

**Comment by pikulet** [comment]
We can follow maid method first.

**Pull request closed without merging**
