### PR TITLE
player cannot be jailed/seanced

### PR DESCRIPTION
**Pull request by starryburst**
inspired by a bug where two people kept seancing the same person, the seanced player wasn't able to talk. this should fix that bug.

only problem is that currently, I believe that the person who gets the seance is the person who joins the game first, which could be unfair.

### CODE REVIEW

**Comment by starryburst** [comment]
apparently the problem is with exclusive meetings but specifically for seance i think this change should probably be made if it is not functionally working currently

**Comment by pikulet** [comment]
I tested this awhile ago, the person can attend both meetings #593

**Comment by starryburst** [comment]
> I tested this awhile ago, the person can attend both meetings #593

okay so realistically i guess its not bugged but i don't really think a jailed person should be able to be jailed twice/a seanced person should be able to be seanced twice but that could be a mechanic adjustement potentially?

**Comment by pikulet** [comment]
I think it's better to fix it inside "exclusive" than in each specific role.

1. Can only attend ONE exclusive meeting each phase
2. Can attend non-exclusive meetings if they are at a higher priority

**Comment by starryburst** [comment]
> I think it's better to fix it inside "exclusive" than in each specific role.
> 
> 1. Can only attend ONE exclusive meeting each phase
> 2. Can attend non-exclusive meetings if they are at a higher priority

Okay yeah that's fine! I still think there's the problem of determining priority between different people with the same priority such as medium/crank, jailer/interrogator

**Comment by pikulet** [comment]
If you want, you can let mafia roles have a higher meeting priority. E.g. gator takes precedence over jailer

between two jailers I don't think there's a good way to determine priority (it's currently using who entered game first as you said!)

**Pull request closed without merging**
