### PR TITLE
Whispers leak now!

### PR DESCRIPTION
**Pull request by DrSharky**
Wow, that was easy.
TESTED with following leak percentages: 0%, 5%, 85%, 100%. Also tested with a game that had whispers disabled. None of the test cases broke, and they worked as expected.

### CODE REVIEW

**Comment by pikulet** [comment]
Fixes #89

**Comment by DrSharky** [comment]
> Fixes #89

Actually it does not. I added a chance for whispers to leak, not a leak whispers button.

**Comment by pikulet** [comment]
ok removed it :) thanks!

**Review by pikulet — APPROVED** [review]
nice

**Pull request merged**
