### PR TITLE
TW: slurs; feat(moderation): add more slurs

### LINKED ISSUE #647: feat(moderation): more slurs to be detected
kiri sent it to me

### PR DESCRIPTION
**Pull request by pikulet**
List by @milkshakesatdawn 
Fixes #647

### CODE REVIEW

**Comment by Kaltzisp** [comment]
Looks like this PR is superseded by #677 , which seems to have the extended list already committed, so going to close this for now.

**Comment by pikulet** [comment]
I don't know how to link the same list for the backend and frontend.

This list in data/moderation is used by the backend to send slurs to the void

The other list in react_main/src/json is used by the frontend to replace slurs with asterisks

If you can make both codes reference the same list it will be the best.

**Comment by Kaltzisp** [comment]
Ahhhh my mistake- I’ll look into using the same one and see if I can get working

**Comment by pikulet** [comment]
I'll rework slurs to only check specific words, and also add support for plurals and wildcards

**Pull request closed without merging**
