### PR TITLE
call popovers for role info in open setups

### PR DESCRIPTION
**Pull request by plokky**
this is for #19

### CODE REVIEW

**Comment by pikulet** [comment]
Hi @plokky , my apologies for the issue description being vague. Firefly was asking for this role description to appear over the roles.

image

You would still need to use popover.onClick like you have done, except that the API should be more similar to 

`onRoleClick` in `Roles.jsx`

**Comment by pikulet** [comment]
It would be good if you can make this popover appear just by scrolling/ clicking

1. The roles at the top
image

2. The setup popover
image

The primary purpose of this function is for players who might not know a role mechanic and find it troublesome to open another tab in a "learn" page.

Thanks so much and looking forward ^~^

**Comment by plokky** [comment]
okie. this branch does 1 already, but i can get it in for the setup popover as well

image

**Comment by plokky** [comment]
i had some time this morning to fix this up.

had to create a secondary display inside the popover. i didn't want to bother making it recursive since i doubt it'd get any deeper than this.

some of the hovering gets wonky if it gets spammed, but it's not too bad. it also creates a backend request for every hover but it should be Etag'd so not really a problem probably but idk what's going on in prod exactly

image

**Comment by r3ndd** [comment]
I think this is good, except I think clicking on the setup row shouldn't show role descriptions. If people want to see them I think they should just hover over the icons in the setup's role list.

**Comment by plokky** [comment]
> I think this is good, except I think clicking on the setup row shouldn't show role descriptions. If people want to see them I think they should just hover over the icons in the setup's role list.

Do you mean it shouldn't appear when on the play/host tab? And probably same with on the player profile?

**Comment by r3ndd** [comment]
> > I think this is good, except I think clicking on the setup row shouldn't show role descriptions. If people want to see them I think they should just hover over the icons in the setup's role list.
> 
> Do you mean it shouldn't appear when on the play/host tab? And probably same with on the player profile?

Anywhere. If you click on the setup row it should show you the setup popover.

**Comment by plokky** [comment]
alright, got that changed

**Comment by pikulet** [comment]
image
image

looks good~

**Pull request merged**
