### PR TITLE
Removed multimeeting from chef

### PR DESCRIPTION
**Pull request by ChaoticNeutralGnome**
Multimeeting is currently bugged https://github.com/r3ndd/BeyondMafia-Integration/issues/326 to silently clear targets if someone dies which causes a lot of vegges with chef

### CODE REVIEW

**Comment by pikulet** [comment]
It's the same issue with voting though, not a multi meeting specific issue

**Comment by ChaoticNeutralGnome** [comment]
> It's the same issue with voting though, not a multi meeting specific issue

Here's an example:

Chef is Person A. They Chef Person B and C. Person D gets shot. Chef vegges

**Comment by pikulet** [comment]
I get what you mean, rend made a similar fix previously for voting.
#62

**Comment by ChaoticNeutralGnome** [comment]
> I get what you mean, rend made a similar fix previously for voting. #62

I don't think this is the same issue. Key here is that the person who dies doesn't have to be involved in the target at all. If ANYONE dies after the chef chooses their targets, the chef will veg

**Comment by pikulet** [comment]
OK get it! Right now chef is the only role with a day multi meeting so we can just patch chef, and fix day multi meetings after.

**Review by DrSharky — APPROVED** [review]

**Review by pikulet — APPROVED** [review]
note: the shot people are treated as nl, so the unshot ones can still attend banquet

**Pull request merged**
